substitutions:
  _REGION: northamerica-northeast2
  _REPOSITORY: yt-clipper
  _TAG: v1

steps:
  - name: gcr.io/cloud-builders/docker
    id: build-migrate
    args:
      - build
      - --target
      - migrate
      - --tag
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/migrate:${_TAG}
      - .

images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/migrate:${_TAG}

timeout: 1200s
