apiVersion: v1
kind: Service
metadata:
  name: temporal-database
  namespace: temporal
spec:
  type: ClusterIP
  clusterIP: None # This makes it a "headless" service
  selector:
    app: temporal-postgres-pod
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
