apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clip-storage
  namespace: yt-clipper
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 50Gi