apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: backend
    newName: northamerica-northeast2-docker.pkg.dev/yt-clipper-gke/yt-clipper/backend
    newTag: 925daf3e944e9bedea432efc7036b6e71c2a263f
  - name: frontend
    newName: northamerica-northeast2-docker.pkg.dev/yt-clipper-gke/yt-clipper/frontend
    newTag: 455f95573b306b9e8b0dd8bf266d783c0454fd45
  - name: migrate
    newName: northamerica-northeast2-docker.pkg.dev/yt-clipper-gke/yt-clipper/migrate
    newTag: 925daf3e944e9bedea432efc7036b6e71c2a263f
